### ISSUE TITLE
Hi, I have a question about hurl installation

### ISSUE THREAD

**Issue by Partysun** [ljgago/nvim-config#1]
Hello
I noticed you have this 
https://github.com/ljgago/nvim-config/blob/81e9dff79d358781e9eb8956c89117cebca96542/lua/config/commons.lua#L45

`-- vim.api.nvim_create_autocmd({ "BufNewFile", "BufRead" }, {
--   pattern = "*.hurl",
--   command = "set filetype=hurl"
-- })
`

I have a problem that hurl filetype is not setuped when I've opened the file. If I do it explicitly using command, syntax highlights and it works perfect. Using this commented code from your config, my nvim works ok finally. The question why did you comment it, probably you resolved the same issue using another way.

**Comment by ljgago** [comment]
Hi, 

I had the same issue with the syntax highlights and I added those lines, but then I installed pfeiferj/nvim-hurl ([lua/plugins/langs/hurl.lua](https://github.com/ljgago/nvim-config/blob/main/lua/plugins/langs/hurl.lua)) and I think those lines were no longer necessary.
